export const FETCHING_PEOPLE_REQUEST = 'FETCHING_PEOPLE_REQUEST';
export const FETCHING_PEOPLE_SUCCESS = 'FETCHING_PEOPLE_SUCCESS';
export const FETCHING_PEOPLE_FAILURE = 'FETCHING_PEOPLE_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOAD_DATA = 'LOAD_DATA';
export const DATA_LOADED = 'DATA_LOADED';
export const AUTH_CHECKED = 'AUTH_CHECKED';